### ISSUE TITLE
invalid format on service

### ISSUE THREAD

**Issue by ljmerza** [BottlecapDave/HomeAssistant-HarvestTimeTracker#4]
hello im trying to send a service to log the timne for a week but i keep getting invalid format without much context

```
{
   "type":"call_service",
   "domain": "harvest_time_tracker",
   "service":"add_time_with_hours",
   "service_data":{
      "project_id":123123,
      "task_id":123123,
      "date":"2023-10-29",
      "hours":8
   },
   "target":{
      "entity_id":"sensor.harvest_time_tracker_123123_hours_week"
   }
}
```

**Comment by BottlecapDave** [comment]
Hi. How are you trying to call the service? I assume not via an automation or similar as it's not yaml? As per the [docs](https://github.com/BottlecapDave/HomeAssistant-HarvestTimeTracker/blob/develop/_docs/services.md#service-harvest_time_trackeradd_time_with_hours), what you have entered should be correct, although I'm not sure about the domain field.

**Comment by BottlecapDave** [comment]
You should get an error in your home assistant logs which at the very bottom have a response which should indicate the possible error

**Comment by ljmerza** [comment]
I was using the websocket through a js script. Looks like a user error though I. My part. Works great thanks!
